In [7]:
#add two matrix
import numpy as np
x=int(input("enter the size of the row: "))
y=int(input("enter the size of the column: "))
arr1=np.random.randint(100,size=(x,y))
print("array1= ",arr1)
arr2=np.random.randint(100,size=(x,y))
print("array2= ",arr2)

sum=arr1+arr2
print ("sum= ",sum)

enter the size of the row: 5
enter the size of the column: 5
array1=  [[22 92 38 65  1]
 [ 7 25 16 25 29]
 [ 8 23 17 12 15]
 [14 66 66 41 77]
 [ 1 16 31  5 82]]
array2=  [[16 88 50 85 63]
 [ 4 64 96  1 31]
 [41 14  0  0 21]
 [78 96 74  2 72]
 [41 14 56 60 88]]
sum=  [[ 38 180  88 150  64]
 [ 11  89 112  26  60]
 [ 49  37  17  12  36]
 [ 92 162 140  43 149]
 [ 42  30  87  65 170]]


In [8]:
#multiply two matrices

import numpy as np
x=int(input("enter the size of the row: "))
y=int(input("enter the size of the column: "))
a=np.random.randint(100,size=(x,y))
b=np.random.randint(100,size=(x,y))
print ("matrix a= ",a)
print("matrix b= ",b)
mul=a*b
print ("multiplication of two matrix=",mul)


enter the size of the row: 5
enter the size of the column: 4
matrix a=  [[12  3 13 53]
 [87 88 38 33]
 [30 80 19 98]
 [ 3 95 38  6]
 [80 54 86 20]]
matrix b=  [[83 69 50 59]
 [88 62 82  7]
 [ 9 81 66 89]
 [16 91 62 91]
 [56 75 77 11]]
multiplication of two matrix= [[ 996  207  650 3127]
 [7656 5456 3116  231]
 [ 270 6480 1254 8722]
 [  48 8645 2356  546]
 [4480 4050 6622  220]]


In [13]:
#transpose of two matrix
import numpy as np
x=int(input("enter the size of the row: "))
y=int(input("enter the size of the column: "))
a=np.random.randint(100,size=(x,y))
b=np.random.randint(100,size=(x,y))
print ("matrix a= ",a)
print("transpose of the matrix a: ",a.T)
print ("matrix b= ",b)
print("transpose of the matrix b: ",b.T)



enter the size of the row: 5
enter the size of the column: 5
matrix a=  [[85 59 54 56 16]
 [30 78 38 17 26]
 [59 88 18 24  0]
 [15 89  2 11 33]
 [46 68 74 61 44]]
transpose of the matrix a:  [[85 30 59 15 46]
 [59 78 88 89 68]
 [54 38 18  2 74]
 [56 17 24 11 61]
 [16 26  0 33 44]]
matrix b=  [[40 77 60 13  3]
 [31 26 21 67 49]
 [90 74 98  2 21]
 [11 49 11 20 26]
 [ 7 12  1 51 14]]
transpose of the matrix b:  [[40 31 90 11  7]
 [77 26 74 49 12]
 [60 21 98 11  1]
 [13 67  2 20 51]
 [ 3 49 21 26 14]]


In [14]:
#get kth column of a matrix
import numpy as np
x=int(input("enter the size of the row: "))
y=int(input("enter the size of the column: "))
a=np.random.randint(100,size=(x,y))
print ("matrix= ",a)
k=int(input("enter the kth column: "))
print("the",k,"th column= ",a[:,k])


enter the size of the row: 5
enter the size of the column: 5
matrix=  [[42 66 86 75  2]
 [39 16 64 65 65]
 [55 39 47  5 97]
 [31  4 10 99 54]
 [63 61 73 43 33]]
enter the kth column: 0
the 0 th column=  [42 39 55 31 63]


In [15]:
#check weather the string is symetric or palindrome
def palindrome(a):
    mid=(len(a)-1)//2
    start=0                
    last=len(a)-1
    flag=0
    while(start<=mid):       
        if(a[start]==a[last]):             
            start+=1
            last-=1             
        else:
            flag=1
            break;    
    if flag == 0:
        print("The entered string is palindrome")
    else:
        print("The entered string is not palindrome")
            
def symmetry(a):     
    n=len(a)
    flag=0     
    if n%2:
        mid=n//2+1
    else:
        mid=n//2         
    start1=0
    start2=mid     
    while(start1<mid and start2<n):         
        if (a[start1]== a[start2]):
            start1=start1+1
            start2=start2+1
        else:
            flag=1
            break      
    if flag==0:
        print("The entered string is symmetrical")
    else:
        print("The entered string is not symmetrical")         
string=input()
palindrome(string)
symmetry(string)

asdasd
The entered string is not palindrome
The entered string is symmetrical
